name: Workflow A

on:
  push:

jobs:
  Job_A_1:
    runs-on: ubuntu-latest
    steps:
      - name: Create one file
        run: |
          echo "Workflow is named: ${{ GIHTUB_RUN_ID }}" > workflow_a.txt
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: workflow_a
          path: workflow_a.txt
        
  Job_A_2:
    runs-on: ubuntu-latest
    steps:
      - name: Create another file
        run: |
          echo "Workflow is named: ${{ GIHTUB_RUN_ID }}" > workflow_b.txt
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: workflow_b
          path: workflow_b.txt
