on:
  pull_request:
  pull_request_target:

jobs:
  job1:
    uses: ./.github/workflows/first_workflow.yml

  job2:
    uses: ./.github/workflows/second_workflow.yml

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: list files
        run: |
          pwd
          ls -lah
